/**
 * EcoSmartHomes Homeowner Help Menu & Explainer Guide ("What Am I Looking At?")
 * Interactive, plain-English explainer for Irish homeowners navigating retrofit data.
 */
(function() {
  'use strict';

  // Section definitions for contextual decoding
  const SECTION_GUIDES = {
    'grants': {
      title: 'SEAI Grants: One-Stop-Shop vs Individual',
      badge: 'Funding & Subsidies',
      summary: 'Grants funded by the Irish government (via SEAI) to pay for a large chunk of your energy upgrades.',
      metrics: [
        { name: 'Gross Cost', desc: 'The contractor\'s full quote before any government money is subtracted.' },
        { name: 'SEAI Grant', desc: 'The government subsidy (up to €50,000 for a deep retrofit or up to €8,000 for a heat pump).' },
        { name: 'Net Outlay', desc: 'The actual money you pay out of pocket or finance via a low-cost Home Energy Loan.' },
        { name: 'OSS vs Individual', desc: 'One-Stop-Shop manages everything and takes the grant off your upfront bill; Individual grants let you hire contractors step-by-step, but you pay upfront and claim reimbursement.' }
      ],
      advice: 'If your home is BER D, E, F, or G, aiming for B2 unlocks the largest One-Stop-Shop subsidies.',
      targetSelector: '#heroGrantSimulator, #grants-matrix, #oss-vs-individual, #grant-calculator'
    },
    'carbon-tax': {
      title: 'Carbon Shield & Fuel Tax Projections',
      badge: 'Cost of Doing Nothing',
      summary: 'Shows the escalating Irish Carbon Tax on home heating oil, gas, and kerosene rising to €100/tonne by 2030.',
      metrics: [
        { name: 'Current Tax', desc: 'Approx €56 per tonne added to every home delivery of oil or gas bill.' },
        { name: '2030 Tax Projection', desc: 'Mandated to rise to €100/tonne, adding €450–€700 extra per year in pure tax alone.' },
        { name: '10-Year Cumulative Penalty', desc: 'The thousands of euros you forfeit to fossil fuel tax if you keep an old boiler.' }
      ],
      advice: 'Upgrading to a heat pump completely eliminates carbon tax liability for heating.',
      targetSelector: '#carbon-tax, #carbonTaxSection, #fuelTaxHike'
    },
    'green-mortgage': {
      title: 'Green Mortgage Bank Interest Slasher',
      badge: 'Mortgage Savings',
      summary: 'Irish banks (AIB, Bank of Ireland, Haven, PTSB) offer discounted interest rates (0.25% to 0.50% lower) for homes rated BER B2 or better.',
      metrics: [
        { name: 'Rate Reduction', desc: 'Typically cuts your mortgage rate by 0.30% to 0.50%.' },
        { name: 'Monthly Payment Cut', desc: 'Saves between €60 and €160 every month on a typical €250k–€400k mortgage.' },
        { name: 'Lifetime Arbitrage', desc: 'Often saves €18,000 to €35,000 in total interest — effectively paying for your retrofit!' }
      ],
      advice: 'Always request an updated post-works BER cert from your assessor and send it straight to your lender.',
      targetSelector: '#green-mortgage, #mortgage-slasher, #greenMortgageSection'
    },
    'heat-pump': {
      title: 'Heat Pump & Radiator Sizer (NSAI SR50-2)',
      badge: 'Heating Engineering',
      summary: 'Evaluates whether your home is thermally tight enough for a heat pump, and if your radiators need resizing.',
      metrics: [
        { name: 'Flow Temperature', desc: 'Heat pumps run at 35°C–45°C (gentle continuous warmth) compared to old oil boilers at 65°C–75°C.' },
        { name: 'Heat Loss Indicator (HLI)', desc: 'Must be 2.0 W/K/m² or lower (or up to 2.3 with special approval) to qualify for an SEAI heat pump grant.' },
        { name: 'Radiator Sizing', desc: 'Because water is cooler, some radiators may need to be upgraded to larger double-panel (Type 22) units.' },
        { name: 'COP (Efficiency)', desc: 'A COP of 3.8 means 1 unit of electricity generates 3.8 units of heat (380% efficiency).' }
      ],
      advice: 'Never install a heat pump before insulating your attic (300mm) and walls, otherwise your running costs will skyrocket.',
      targetSelector: '#heat-pump, #heatPumpSection, #radiatorSizer, #nsai-sr50'
    },
    'solar-pv': {
      title: 'Solar PV & Regional Micro-Climate Harvest',
      badge: 'Clean Electricity',
      summary: 'Calculates the electricity generated by solar panels on your roof, battery storage, and export revenue.',
      metrics: [
        { name: 'Array Size (kWp)', desc: 'Peak capacity in full sunlight. Typical Irish homes install 4.2 kWp to 6.5 kWp (10 to 16 panels).' },
        { name: 'Annual Generation', desc: 'A standard 4.5 kWp system produces approx 4,000 to 4,400 kWh of clean power per year.' },
        { name: 'CEG Export Tariff', desc: 'Clean Export Guarantee: Irish energy suppliers pay you 21c to 24c per kWh for surplus electricity sent back to the grid.' },
        { name: 'Battery Storage', desc: 'Stores daytime solar for evening use and can charge overnight on cheap night rates (e.g. 8c–10c EV tariffs).' }
      ],
      advice: 'Solar PV in Ireland now qualifies for 0% VAT and up to €2,100 in SEAI microgeneration grants.',
      targetSelector: '#solar-pv, #solarSection, #solarHarvestMap, #solarYield'
    },
    'ber-matrix': {
      title: 'BER Rating & Fabric-First Progression',
      badge: 'Energy Efficiency',
      summary: 'Shows your home\'s Building Energy Rating (A1 to G) and the sequence of steps needed to jump grades.',
      metrics: [
        { name: 'Primary Energy (kWh/m²/yr)', desc: 'The official rating metric. Lower number = lower energy use.' },
        { name: 'B2 Target', desc: 'The golden benchmark in Ireland. Unlocks deep retrofit grants, green mortgages, and heat pump viability.' },
        { name: 'Fabric-First', desc: 'The proven rule: stop heat escaping through roof, walls, and windows before spending money on heating systems.' }
      ],
      advice: 'Attic insulation is the cheapest upgrade with the fastest payback (usually under 3 years).',
      targetSelector: '#ber-matrix, #berSection, #berJumpMatrix, #berAdvisor'
    },
    'quote-audit': {
      title: 'Contractor Quote Comparator & Red-Liner',
      badge: 'Conflict-Free Audit',
      summary: 'Scans and audits contractor quotes to spot inflated pricing, missing SEAI equipment certifications, or hidden costs.',
      metrics: [
        { name: 'Equipment Line Items', desc: 'Ensures the quote lists specific heat pump models, solar inverters, and insulation thicknesses.' },
        { name: 'SEAI Registered Provider', desc: 'Checks if the installer is certified so your grant application will not be rejected.' },
        { name: 'Apples-to-Apples Pricing', desc: 'Normalizes quotes to cost per m² or cost per kW so you can spot 30%+ markups.' }
      ],
      advice: 'Never sign a quote or pay a deposit before checking if the heat pump model is on the SEAI Triple-E register.',
      targetSelector: '#quote-audit, #quoteComparator, #tenderGenerator'
    }
  };

  // Jargon Glossary
  const JARGON_TERMS = [
    {
      term: 'BER (Building Energy Rating)',
      badge: 'Core Metric',
      definition: 'An energy label for your home from A1 (most efficient, passive house) down to G (least efficient, cold & draughty). Measured in kWh/m²/year.',
      analogy: 'Like the energy rating sticker on a fridge, but for your entire home.'
    },
    {
      term: 'B2 Threshold',
      badge: 'Target Grade',
      definition: 'The official energy threshold required in Ireland to qualify for One-Stop-Shop grants and discounted Green Mortgage rates (≤125 kWh/m²/yr).',
      analogy: 'The "grade B" pass mark that unlocks all government bonuses and bank discounts.'
    },
    {
      term: 'Fabric-First',
      badge: 'Golden Rule',
      definition: 'Upgrading insulation (attic, walls, floors) and air tightness before installing renewable heating equipment like a heat pump.',
      analogy: 'Putting on a thick winter coat before turning on a heater.'
    },
    {
      term: 'HLI (Heat Loss Indicator)',
      badge: 'Engineering',
      definition: 'A calculation of how many Watts of heat escape per degree of temperature difference per square meter. Must be ≤ 2.0 W/K/m² for SEAI heat pump grants.',
      analogy: 'A measurement of how "leaky" your home\'s thermal bucket is.'
    },
    {
      term: 'One-Stop-Shop (OSS)',
      badge: 'SEAI Pathway',
      definition: 'An SEAI-registered deep retrofit company that manages the entire project from survey to completion and deducts the grant directly from your upfront bill.',
      analogy: 'A turnkey full-service builder who handles all red tape, paperwork, and grant deductions.'
    },
    {
      term: 'Individual Energy Upgrades',
      badge: 'SEAI Pathway',
      definition: 'The step-by-step grant route where you hire SEAI-registered contractors directly for specific jobs (e.g., just attic, or just solar). You pay first and claim back.',
      analogy: 'The DIY project management route where you tackle one room or measure at a time.'
    },
    {
      term: 'CEG (Clean Export Guarantee)',
      badge: 'Solar Revenue',
      definition: 'The legal tariff Irish energy suppliers must pay you for each unit (kWh) of microgeneration electricity you export back to the national grid (approx 21c–24c/kWh).',
      analogy: 'Selling your home-grown surplus solar power back to the electricity company.'
    },
    {
      term: 'COP (Coefficient of Performance)',
      badge: 'Heat Pump',
      definition: 'The efficiency ratio of a heat pump. A COP of 4.0 means for every 1 unit of electricity consumed, it outputs 4 units of heat energy (400% efficiency).',
      analogy: 'Putting €1 in and getting €4 worth of warmth back out.'
    },
    {
      term: 'kWp (Kilowatt-Peak)',
      badge: 'Solar Capacity',
      definition: 'The maximum theoretical power output of a solar PV array under standardized direct laboratory sunlight test conditions.',
      analogy: 'The horsepower rating of your solar panel system.'
    },
    {
      term: 'U-Value',
      badge: 'Insulation',
      definition: 'The rate of heat loss through a building element (wall, window, roof). The lower the U-value, the better the insulation.',
      analogy: 'Like holes in a colander: smaller holes mean less water (heat) leaks out.'
    },
    {
      term: 'Green Mortgage Arbitrage',
      badge: 'Finance',
      definition: 'Refinancing your home loan onto a green mortgage after achieving a B2 BER. The interest rate reduction (0.25%–0.50%) produces monthly cash savings.',
      analogy: 'Getting a permanent discount on your mortgage because your house is energy efficient.'
    },
    {
      term: 'NSAI SR50-2',
      badge: 'Irish Standard',
      definition: 'The Irish National Standards Authority code of practice for designing domestic heating systems with low-temperature heat pumps and correctly sized radiators.',
      analogy: 'The official plumbing and heating rulebook for Irish heat pump installations.'
    }
  ];

  // 5 Costly Traps
  const RETROFIT_TRAPS = [
    {
      title: '1. The "Heat Pump First" Trap',
      desc: 'Installing a heat pump into an uninsulated house (BER E, F, or G). The heat pump will run 24/7 at maximum capacity, consume massive amounts of electricity, and the house will still feel cold. Always insulate first!'
    },
    {
      title: '2. Missing Out on Green Mortgage Slashes',
      desc: 'Many homeowners spend €30,000+ on upgrades, reach an A3 BER rating, but forget to send the new BER certificate to their mortgage bank to unlock the 0.35%+ interest rate discount. That is leaving €1,000+/year on the table.'
    },
    {
      title: '3. Solar PV on an Old Roof',
      desc: 'Mounting solar panels on 35-year-old roof tiles or perished felt. When the roof leaks in 3 years, you have to pay €1,500+ just to unmount and reinstall the panels. Fix or inspect the roof structure before mounting panels.'
    },
    {
      title: '4. Accepting Quotes Without Model Numbers',
      desc: 'Contractors quoting generic terms like "6kW Heat Pump" or "Tier 1 Solar Panels" without naming the manufacturer (e.g. Daikin, Mitsubishi, Viessmann). SEAI grants require approved models on the Triple-E register.'
    },
    {
      title: '5. Overpaying VAT on Solar & Retrofit Works',
      desc: 'In Ireland, domestic solar PV installations are zero-rated for VAT (0%). Ensure your contractor does not add 13.5% VAT to solar installations.'
    }
  ];

  // State
  let currentActiveTab = 'decode';
  let triageState = { era: '', goal: '' };

  // DOM Ingestion & Setup
  function initHomeownerGuide() {
    if (document.getElementById('esh-help-drawer')) return;

    // 1. Inject Floating Trigger Button (Bottom-Right)
    if (!document.getElementById('esh-help-floating-btn')) {
      const floatBtn = document.createElement('button');
      floatBtn.id = 'esh-help-floating-btn';
      floatBtn.type = 'button';
      floatBtn.setAttribute('aria-label', 'Open Homeowner Guide & Explainer');
      floatBtn.innerHTML = `
        <span class="esh-guide-pulse-dot"></span>
        <span>💡 Guide: What Am I Looking At?</span>
      `;
      floatBtn.onclick = () => window.openHomeownerGuide();
      document.body.appendChild(floatBtn);
    }

    // 2. Inject Backdrop
    const backdrop = document.createElement('div');
    backdrop.id = 'esh-help-backdrop';
    backdrop.onclick = () => window.closeHomeownerGuide();
    document.body.appendChild(backdrop);

    // 3. Inject Drawer DOM
    const drawer = document.createElement('aside');
    drawer.id = 'esh-help-drawer';
    drawer.setAttribute('aria-label', 'Homeowner Explainer and Field Guide');
    drawer.innerHTML = `
      <div class="esh-help-header">
        <div class="esh-help-title-group">
          <div class="esh-help-icon-box">💡</div>
          <div>
            <h3 class="esh-help-title">Homeowner Field Guide</h3>
            <div class="esh-help-subtitle">What Am I Looking At? (Irish Retrofit Decoder)</div>
          </div>
        </div>
        <button type="button" class="esh-help-close-btn" onclick="window.closeHomeownerGuide()" aria-label="Close Guide">✕</button>
      </div>

      <div class="esh-help-search-wrap">
        <div class="esh-help-search-box">
          <span style="color:#34f5c5; font-size: 0.95rem;">🔍</span>
          <input type="text" id="esh-help-search-input" placeholder="Search terms (e.g., BER, HLI, Heat Pump, Grant, B2, Solar...)" oninput="window.filterHomeownerJargon(this.value)">
        </div>
      </div>

      <nav class="esh-help-tabs" aria-label="Guide Sections">
        <button type="button" class="esh-help-tab-btn active" data-tab="decode" onclick="window.switchHomeownerGuideTab('decode')">📍 Decode This View</button>
        <button type="button" class="esh-help-tab-btn" data-tab="jargon" onclick="window.switchHomeownerGuideTab('jargon')">📖 Jargon Buster</button>
        <button type="button" class="esh-help-tab-btn" data-tab="triage" onclick="window.switchHomeownerGuideTab('triage')">🧭 Where Do I Start?</button>
        <button type="button" class="esh-help-tab-btn" data-tab="traps" onclick="window.switchHomeownerGuideTab('traps')">⚠️ 5 Traps</button>
        <button type="button" class="esh-help-tab-btn" data-tab="voice" onclick="window.switchHomeownerGuideTab('voice')">🎙️ Ask Aoife</button>
      </nav>

      <div class="esh-help-body" id="esh-help-body-content">
        
        <!-- TAB 1: DECODE THIS VIEW -->
        <div class="esh-tab-panel active" id="tab-panel-decode">
          <div style="margin-bottom: 14px; font-size: 0.8rem; color: #94a3b8; display: flex; align-items: center; justify-content: space-between;">
            <span>Select a dashboard feature to demystify:</span>
            <span id="esh-active-view-tag" style="color: #34f5c5; font-weight: 700; font-family: monospace;">Auto-Detected</span>
          </div>
          <div id="esh-section-cards-container"></div>
        </div>

        <!-- TAB 2: JARGON BUSTER -->
        <div class="esh-tab-panel" id="tab-panel-jargon">
          <div style="margin-bottom: 12px; font-size: 0.8rem; color: #94a3b8;">
            Clear, no-nonsense definitions of Irish home energy terms and acronyms:
          </div>
          <div id="esh-jargon-list-container"></div>
        </div>

        <!-- TAB 3: WHERE DO I START? -->
        <div class="esh-tab-panel" id="tab-panel-triage">
          <div style="margin-bottom: 14px; font-size: 0.82rem; color: #cbd5e1; line-height: 1.5;">
            Not sure where to begin? Answer these 2 quick questions to get an instant, logical recommendation for your home:
          </div>

          <div class="esh-triage-step-box">
            <strong style="color: #ffffff; font-size: 0.85rem;">Step 1: When was your home built?</strong>
            <div class="esh-triage-options" id="triage-era-options">
              <button type="button" class="esh-triage-opt-btn" onclick="window.selectTriageOption('era', 'pre1975')">🏚️ Pre-1975<br><span style="font-size:0.68rem;opacity:0.8;">Hollow block / Solid wall</span></button>
              <button type="button" class="esh-triage-opt-btn" onclick="window.selectTriageOption('era', '1975-2000')">🏡 1975–2000<br><span style="font-size:0.68rem;opacity:0.8;">Cavity block / Semi-D</span></button>
              <button type="button" class="esh-triage-opt-btn" onclick="window.selectTriageOption('era', '2000-2011')">🏠 2000–2011<br><span style="font-size:0.68rem;opacity:0.8;">Modern building regs</span></button>
              <button type="button" class="esh-triage-opt-btn" onclick="window.selectTriageOption('era', 'post2011')">✨ Post-2011<br><span style="font-size:0.68rem;opacity:0.8;">A/B Rated / Part L</span></button>
            </div>
          </div>

          <div class="esh-triage-step-box">
            <strong style="color: #ffffff; font-size: 0.85rem;">Step 2: What is your primary priority?</strong>
            <div class="esh-triage-options" id="triage-goal-options">
              <button type="button" class="esh-triage-opt-btn" onclick="window.selectTriageOption('goal', 'draughts')">🥶 Stop Cold & Draughts<br><span style="font-size:0.68rem;opacity:0.8;">Warmth & Comfort</span></button>
              <button type="button" class="esh-triage-opt-btn" onclick="window.selectTriageOption('goal', 'bills')">📉 Slash High Fuel Bills<br><span style="font-size:0.68rem;opacity:0.8;">Oil / Gas Inflation</span></button>
              <button type="button" class="esh-triage-opt-btn" onclick="window.selectTriageOption('goal', 'heatpump')">♨️ Install Heat Pump<br><span style="font-size:0.68rem;opacity:0.8;">Zero Fossil Fuels</span></button>
              <button type="button" class="esh-triage-opt-btn" onclick="window.selectTriageOption('goal', 'solar')">☀️ Solar PV Power<br><span style="font-size:0.68rem;opacity:0.8;">Clean Electricity</span></button>
              <button type="button" class="esh-triage-opt-btn" onclick="window.selectTriageOption('goal', 'mortgage')">🏦 Green Mortgage Cut<br><span style="font-size:0.68rem;opacity:0.8;">Bank Rate Arbitrage</span></button>
            </div>
          </div>

          <div class="esh-triage-result" id="esh-triage-result-box">
            <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 8px;">
              <span style="font-size: 1.2rem;">🎯</span>
              <strong style="color: #34f5c5; font-size: 0.95rem;">Your Recommended First Step:</strong>
            </div>
            <div id="esh-triage-result-text" style="font-size: 0.82rem; color: #f8fafc; line-height: 1.55;"></div>
            <a href="#heroGrantSimulator" id="esh-triage-jump-btn" class="esh-jump-btn" onclick="window.closeHomeownerGuide()">Open Recommended Tool ➜</a>
          </div>
        </div>

        <!-- TAB 4: 5 TRAPS -->
        <div class="esh-tab-panel" id="tab-panel-traps">
          <div style="margin-bottom: 14px; font-size: 0.8rem; color: #f87171; font-weight: 700;">
            Avoid these 5 costly mistakes Irish homeowners frequently make:
          </div>
          <div id="esh-traps-list-container"></div>
        </div>

        <!-- TAB 5: ASK AOIFE -->
        <div class="esh-tab-panel" id="tab-panel-voice">
          <div style="margin-bottom: 14px; font-size: 0.82rem; color: #cbd5e1; line-height: 1.5;">
            Have a question in plain English? Speak directly with <strong>Aoife</strong>, our independent AI Homeowner Energy Advisor, or tap any question below:
          </div>

          <div class="esh-aoife-prompt-chip" onclick="window.askAoifePrompt('What grants are available for my home in 2026?')">
            <span>💶 "What grants are available for my home in 2026?"</span>
            <span>➜</span>
          </div>
          <div class="esh-aoife-prompt-chip" onclick="window.askAoifePrompt('Is my house suitable for an air-to-water heat pump?')">
            <span>♨️ "Is my house suitable for an air-to-water heat pump?"</span>
            <span>➜</span>
          </div>
          <div class="esh-aoife-prompt-chip" onclick="window.askAoifePrompt('How much can a Green Mortgage save me if I reach B2?')">
            <span>🏦 "How much can a Green Mortgage save me if I reach B2?"</span>
            <span>➜</span>
          </div>
          <div class="esh-aoife-prompt-chip" onclick="window.askAoifePrompt('What is the difference between One-Stop-Shop and individual grants?')">
            <span>📋 "What is the difference between One-Stop-Shop and individual grants?"</span>
            <span>➜</span>
          </div>
          <div class="esh-aoife-prompt-chip" onclick="window.askAoifePrompt('How does the solar Clean Export Guarantee (CEG) work?')">
            <span>☀️ "How does the solar Clean Export Guarantee (CEG) work?"</span>
            <span>➜</span>
          </div>

          <div style="margin-top: 20px; text-align: center;">
            <button type="button" onclick="window.launchAoifeAdvisorFull()" style="background: #10b981; color: #00241b; border: none; border-radius: 12px; font-weight: 900; font-size: 0.85rem; padding: 12px 20px; cursor: pointer; display: inline-flex; align-items: center; gap: 8px;">
              <span>🎙️ Start Audio Voice Chat with Aoife</span>
            </button>
          </div>
        </div>

      </div>
    `;

    document.body.appendChild(drawer);

    // Populate Dynamic Content
    renderSectionCards();
    renderJargonList(JARGON_TERMS);
    renderTrapsList();
    bindKeyboardShortcuts();
    injectContextualBadges();
  }

  // Render Section Cards in Tab 1
  function renderSectionCards(highlightKey) {
    const container = document.getElementById('esh-section-cards-container');
    if (!container) return;

    let html = '';
    for (const [key, sec] of Object.entries(SECTION_GUIDES)) {
      const isHigh = key === highlightKey;
      html += `
        <div class="esh-guide-card ${isHigh ? 'highlight' : ''}" id="esh-card-${key}">
          <div class="esh-card-header">
            <span class="esh-card-badge">${sec.badge}</span>
            <span style="font-size: 0.72rem; color: #34f5c5; font-family: monospace;">#${key}</span>
          </div>
          <h4 class="esh-card-title">${sec.title}</h4>
          <p class="esh-card-p">${sec.summary}</p>
          <ul class="esh-metrics-list">
            ${sec.metrics.map(m => `
              <li class="esh-metric-item">
                <span class="esh-metric-name">${m.name}</span>
                <span class="esh-metric-plain">${m.desc}</span>
              </li>
            `).join('')}
          </ul>
          <div class="esh-homeowner-takeaway">
            <span>💡</span>
            <span><strong>Homeowner Takeaway:</strong> ${sec.advice}</span>
          </div>
          <button type="button" class="esh-jump-btn" onclick="window.jumpToPageSection('${sec.targetSelector}')">
            View This Tool On Page ➜
          </button>
        </div>
      `;
    }
    container.innerHTML = html;
  }

  // Render Jargon Terms in Tab 2
  function renderJargonList(terms) {
    const container = document.getElementById('esh-jargon-list-container');
    if (!container) return;

    if (terms.length === 0) {
      container.innerHTML = `<div style="color: #94a3b8; font-size: 0.85rem; padding: 20px; text-align: center;">No terms matched your search. Try searching "BER", "Grant", "Solar", or "Heat Pump".</div>`;
      return;
    }

    container.innerHTML = terms.map(item => `
      <div class="esh-jargon-entry">
        <div class="esh-jargon-term">
          <span>${item.term}</span>
          <span class="esh-card-badge" style="font-size:0.62rem;">${item.badge}</span>
        </div>
        <div style="font-size: 0.8rem; color: #cbd5e1; line-height: 1.5;">${item.definition}</div>
        <div class="esh-jargon-analogy">💡 Plain-English: "${item.analogy}"</div>
      </div>
    `).join('');
  }

  // Render Traps in Tab 4
  function renderTrapsList() {
    const container = document.getElementById('esh-traps-list-container');
    if (!container) return;

    container.innerHTML = RETROFIT_TRAPS.map(t => `
      <div class="esh-trap-card">
        <h4>⚠️ ${t.title}</h4>
        <p>${t.desc}</p>
      </div>
    `).join('');
  }

  // Detect which section is currently on screen
  function detectCurrentSection() {
    const scrollPos = window.scrollY + 200;
    let closestKey = 'grants';

    for (const [key, sec] of Object.entries(SECTION_GUIDES)) {
      const el = document.querySelector(sec.targetSelector);
      if (el) {
        const top = el.offsetTop;
        const height = el.offsetHeight;
        if (scrollPos >= top && scrollPos <= top + height) {
          closestKey = key;
          break;
        }
      }
    }
    return closestKey;
  }

  // Inject Contextual Badges ("ℹ️ What is this?") into existing sections
  function injectContextualBadges() {
    for (const [key, sec] of Object.entries(SECTION_GUIDES)) {
      const selectors = sec.targetSelector.split(', ');
      for (const sel of selectors) {
        const target = document.querySelector(sel);
        if (target && !target.querySelector(`.esh-badge-${key}`)) {
          const header = target.querySelector('h2, h3, .section-title-wrapper') || target;
          const badge = document.createElement('a');
          badge.className = `esh-context-help-trigger esh-badge-${key}`;
          badge.href = 'javascript:void(0)';
          badge.setAttribute('title', `Explain: ${sec.title}`);
          badge.innerHTML = `<span>ℹ️ Explain</span>`;
          badge.onclick = (e) => {
            e.preventDefault();
            e.stopPropagation();
            window.openHomeownerGuide(key, 'decode');
          };
          header.appendChild(badge);
          break;
        }
      }
    }
  }

  // Switch Tab
  window.switchHomeownerGuideTab = function(tabKey) {
    currentActiveTab = tabKey;
    const tabBtns = document.querySelectorAll('.esh-help-tab-btn');
    const panels = document.querySelectorAll('.esh-tab-panel');

    tabBtns.forEach(btn => {
      btn.classList.toggle('active', btn.getAttribute('data-tab') === tabKey);
    });

    panels.forEach(p => {
      p.classList.toggle('active', p.id === `tab-panel-${tabKey}`);
    });
  };

  // Open Guide
  window.openHomeownerGuide = function(targetSectionKey, initialTab) {
    const backdrop = document.getElementById('esh-help-backdrop');
    const drawer = document.getElementById('esh-help-drawer');
    if (!backdrop || !drawer) return;

    backdrop.classList.add('active');
    drawer.classList.add('open');
    document.body.style.overflow = 'hidden';

    const activeKey = targetSectionKey || detectCurrentSection();
    renderSectionCards(activeKey);

    const tag = document.getElementById('esh-active-view-tag');
    if (tag && SECTION_GUIDES[activeKey]) {
      tag.textContent = SECTION_GUIDES[activeKey].title;
    }

    if (initialTab) {
      window.switchHomeownerGuideTab(initialTab);
    } else {
      window.switchHomeownerGuideTab('decode');
    }

    // Scroll to highlighted card if in decode tab
    if (targetSectionKey) {
      setTimeout(() => {
        const card = document.getElementById(`esh-card-${targetSectionKey}`);
        if (card) {
          card.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
      }, 200);
    }
  };

  // Close Guide
  window.closeHomeownerGuide = function() {
    const backdrop = document.getElementById('esh-help-backdrop');
    const drawer = document.getElementById('esh-help-drawer');
    if (backdrop && drawer) {
      backdrop.classList.remove('active');
      drawer.classList.remove('open');
      document.body.style.overflow = '';
    }
  };

  // Jump to specific tool on page and close guide
  window.jumpToPageSection = function(selectorList) {
    window.closeHomeownerGuide();
    const selectors = selectorList.split(', ');
    let found = false;
    for (const sel of selectors) {
      const el = document.querySelector(sel);
      if (el) {
        found = true;
        setTimeout(() => {
          el.scrollIntoView({ behavior: 'smooth', block: 'center' });
        }, 150);
        break;
      }
    }
    if (!found) {
      const primary = selectors[0].startsWith('#') ? selectors[0] : `#${selectors[0]}`;
      window.location.href = `/${primary}`;
    }
  };

  // Filter Jargon Terms
  window.filterHomeownerJargon = function(query) {
    window.switchHomeownerGuideTab('jargon');
    const q = (query || '').toLowerCase().trim();
    if (!q) {
      renderJargonList(JARGON_TERMS);
      return;
    }

    const filtered = JARGON_TERMS.filter(item => 
      item.term.toLowerCase().includes(q) ||
      item.definition.toLowerCase().includes(q) ||
      item.badge.toLowerCase().includes(q) ||
      item.analogy.toLowerCase().includes(q)
    );
    renderJargonList(filtered);
  };

  // Triage Selection Logic
  window.selectTriageOption = function(step, value) {
    triageState[step] = value;

    // Toggle button style in DOM
    const container = document.getElementById(`triage-${step}-options`);
    if (container) {
      container.querySelectorAll('.esh-triage-opt-btn').forEach(btn => {
        btn.classList.remove('selected');
      });
      event.currentTarget.classList.add('selected');
    }

    // Calculate recommendation if both selected
    if (triageState.era && triageState.goal) {
      evaluateTriage();
    }
  };

  function evaluateTriage() {
    const resultBox = document.getElementById('esh-triage-result-box');
    const resultText = document.getElementById('esh-triage-result-text');
    const jumpBtn = document.getElementById('esh-triage-jump-btn');
    if (!resultBox || !resultText) return;

    let rec = '';
    let target = '#heroGrantSimulator';
    let btnText = 'Open Grant & Retrofit Simulator ➜';

    const { era, goal } = triageState;

    if (era === 'pre1975') {
      if (goal === 'heatpump') {
        rec = '<strong>Fabric Warning:</strong> Pre-1975 homes typically have an HLI > 3.0 W/K/m². You MUST complete 300mm attic insulation and external/internal wall drylining first before installing a heat pump, otherwise grant approval will be refused.';
        target = '#heroGrantSimulator';
      } else {
        rec = '<strong>Fabric-First Priority:</strong> For pre-1975 homes, start with 300mm attic insulation (€1,500 SEAI grant) and external wall insulation (up to €8,000 grant). This eliminates 50%+ of heat loss immediately.';
        target = '#heroGrantSimulator';
      }
    } else if (era === '1975-2000') {
      if (goal === 'bills' || goal === 'draughts') {
        rec = '<strong>Best Value Upgrade:</strong> Pumped cavity bead wall insulation + 300mm attic insulation. This costs under €3,500 net after grants, takes 1 day to install, and saves €800+/year.';
        target = '#heroGrantSimulator';
      } else if (goal === 'heatpump') {
        rec = '<strong>High Suitability:</strong> 1975–2000 cavity wall homes become heat-pump ready with pumped cavities and attic top-up. Sizing your radiators using our NSAI SR50-2 calculator is your next step.';
        target = '#nsai-sr50, #heatPumpSection';
        btnText = 'Open Radiator & Heat Pump Sizer ➜';
      } else {
        rec = '<strong>One-Stop-Shop Candidate:</strong> Jumping from BER D/E to B2 is straightforward on 1975–2000 homes and unlocks €25,000+ in One-Stop-Shop grant deductions.';
        target = '#grants-matrix';
      }
    } else if (era === '2000-2011') {
      if (goal === 'solar') {
        rec = '<strong>Prime Solar Candidate:</strong> Your roof structure and electrical wiring are modern. Install a 4.5–6kWp Solar PV system with a battery to wipe out 70% of day electricity usage.';
        target = '#solar-pv, #solarHarvestMap';
        btnText = 'Open Solar Harvest Calculator ➜';
      } else if (goal === 'mortgage') {
        rec = '<strong>Quick Green Mortgage Win:</strong> Your home is likely already C1–C3. A simple attic top-up or heat pump easily pushes you over the B2 threshold, unlocking a 0.35%+ interest rate discount from Irish banks.';
        target = '#green-mortgage, #mortgage-slasher';
        btnText = 'Calculate Mortgage Savings ➜';
      } else {
        rec = '<strong>Heat Pump Ready:</strong> 2000–2011 homes usually meet the HLI ≤ 2.0 threshold with minimal fabric work. You can transition away from home heating oil directly.';
        target = '#nsai-sr50, #heatPumpSection';
        btnText = 'Open Heat Pump Sizer ➜';
      }
    } else { // post2011
      rec = '<strong>Microgeneration & Optimization:</strong> Post-2011 homes already have high insulation levels. Your highest ROI moves are Solar PV (0% VAT), battery arbitrage for cheap night rates (8c/kWh), and smart heating controls.';
      target = '#solar-pv, #solarHarvestMap';
      btnText = 'Calculate Solar PV Savings ➜';
    }

    resultText.innerHTML = rec;
    if (jumpBtn) {
      jumpBtn.textContent = btnText;
      jumpBtn.onclick = () => window.jumpToPageSection(target);
    }
    resultBox.classList.add('active');
  }

  // Ask Aoife voice prompt
  window.askAoifePrompt = function(question) {
    window.closeHomeownerGuide();
    if (window.showEshToast) {
      window.showEshToast(`Asking Aoife: "${question}"`, '🎙️');
    }
    if (window.AoifeBriefing && typeof window.AoifeBriefing.ask === 'function') {
      window.AoifeBriefing.ask(question);
    } else if (typeof window.dismissPersonaModal === 'function') {
      window.dismissPersonaModal('homeowner');
      const launcher = document.getElementById('eshVoiceAdvisorLauncher');
      if (launcher) launcher.click();
    }
  };

  window.launchAoifeAdvisorFull = function() {
    window.closeHomeownerGuide();
    if (typeof window.dismissPersonaModal === 'function') {
      window.dismissPersonaModal('homeowner');
    }
    const launcher = document.getElementById('eshVoiceAdvisorLauncher');
    if (launcher) {
      launcher.click();
    } else if (window.showEshToast) {
      window.showEshToast('Connecting to Aoife, your Homeowner Energy Advisor...', '🎙️');
    }
  };

  // Keyboard Shortcuts: Press "?" or "h" to toggle guide, "Escape" to close
  function bindKeyboardShortcuts() {
    document.addEventListener('keydown', (e) => {
      const activeTag = document.activeElement ? document.activeElement.tagName : '';
      if (activeTag === 'INPUT' || activeTag === 'TEXTAREA' || activeTag === 'SELECT') {
        return;
      }
      if (e.key === '?' || (e.key === 'h' && !e.ctrlKey && !e.metaKey)) {
        e.preventDefault();
        const drawer = document.getElementById('esh-help-drawer');
        if (drawer && drawer.classList.contains('open')) {
          window.closeHomeownerGuide();
        } else {
          window.openHomeownerGuide();
        }
      } else if (e.key === 'Escape') {
        window.closeHomeownerGuide();
      }
    });
  }

  // Auto-init on DOM ready
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initHomeownerGuide);
  } else {
    initHomeownerGuide();
  }

})();
