/**
 * EcoSmartHome Weekly Funnel Performance Reporter (Vercel Serverless Cron Endpoint)
 * 
 * This script runs as a secured Vercel Serverless Function or Next.js Route Handler.
 * It is designed to be triggered every Monday morning via Vercel Crons, query the Supabase 
 * telemetry views, compile a clean markdown/HTML summary table of the conversion rates 
 * and funnel bottlenecks, and instantly dispatch the digest to Joe's inbox using Resend (or SendGrid).
 * 
 * Setup Prerequisites:
 *   npm install @supabase/supabase-js resend @sendgrid/mail
 * 
 * Environment Variables required in Vercel:
 *   - SUPABASE_URL: Your Supabase Project API URL
 *   - SUPABASE_SERVICE_ROLE_KEY: Secure backend access bypass key to query analytics
 *   - RESEND_API_KEY (or SENDGRID_API_KEY): Email provider credential
 *   - CRON_SECRET: Secret key generated by Vercel to verify the cron request signature
 *   - JOE_EMAIL: Joe's destination inbox (e.g., joe@ecosmarthomes.ie)
 */

import { createClient } from '@supabase/supabase-js';
import { Resend } from 'resend';
import sgMail from '@sendgrid/mail';

// Initialize Supabase Client with administrative bypass role
const supabase = createClient(
  process.env.SUPABASE_URL || '',
  process.env.SUPABASE_SERVICE_ROLE_KEY || ''
);

// Initialize Mail Clients
const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;
if (process.env.SENDGRID_API_KEY) {
  sgMail.setApiKey(process.env.SENDGRID_API_KEY);
}

export default async function handler(req, res) {
  // 1. Secure the endpoint against unauthorized execution
  const authHeader = req.headers.get?.('authorization') || req.headers?.authorization;
  if (process.env.NODE_ENV === 'production') {
    if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
      return new Response(JSON.stringify({ error: 'Unauthorized Cron Trigger' }), {
        status: 401,
        headers: { 'Content-Type': 'application/json' },
      });
    }
  }

  try {
    console.log('📊 Querying EcoSmartHome telemetry views...');

    // 2. Query the complete funnel conversion progression view
    const { data: funnelStats, error: funnelError } = await supabase
      .from('v_wizard_conversion_funnel')
      .select('*')
      .order('step', { ascending: true });

    if (funnelError) throw funnelError;

    // 3. Query the prioritized drop-off bottlenecks view
    const { data: bottlenecks, error: bottleneckError } = await supabase
      .from('v_wizard_dropoff_bottlenecks')
      .select('*')
      .order('dropoff_count', { ascending: true });

    if (bottleneckError) throw bottleneckError;

    // 4. Generate the Markdown Content for the Digest Email
    const reportDate = new Date().toLocaleDateString('en-IE', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    const emailSubject = `📊 EcoSmartHome Funnel Report — Monday, ${new Date().toLocaleDateString('en-IE')}`;
    
    // Compile dynamic Markdown
    let markdownBody = `
# 🚀 Weekly Onboarding Funnel Performance Digest
**EcoSmartHome Ireland — Independent Retrofit Advisory**  
*Report generated on: ${reportDate}*

---

### 📈 Conversion Funnel Progression Scorecard
Tracks active customer progression rates and final checkout clicks through the 5-step onboarding wizard.

| Step | Page View / Action | Unique Views | Completed Count | Step Retention % | Overall Conversion % |
| :---: | :--- | :---: | :---: | :---: | :---: |
${(funnelStats || []).map(row => {
  const stepName = getStepFriendlyName(row.step);
  return `| **Step ${row.step}** | ${stepName} | ${(row.unique_views || 0).toLocaleString('en-IE')} | ${(row.completed_count || 0).toLocaleString('en-IE')} | **${row.step_retention_rate || 0}%** | **${row.overall_conversion_rate || 0}%** |`;
}).join('\n')}

---

### ⚠️ Prioritized Drop-Off Bottlenecks (Friction Hotspots)
These are the steps where Irish homeowners are dropping out of the onboarding modal. Resolve these to unlock higher Stripe conversions.

| Step | Vulnerable Interface | Drop-offs | Drop-off % | Recommended Optimization Action |
| :---: | :--- | :---: | :---: | :--- |
${(bottlenecks || []).map(row => {
  const stepName = getStepFriendlyName(row.step);
  const recommendation = getActionRecommendation(row.step);
  return `| **Step ${row.step}** | ${stepName} | **${row.dropoff_count || 0}** users | **${row.dropoff_rate || 0}%** | ${recommendation} |`;
}).join('\n')}

---

### 💡 Joe's Conversion Optimization Dashboard Action Items
Based on this morning's live telemetry telemetry:
1. **Attic/Boiler Photo Uploads (Step 3):** If user drop-offs exceed 20%, ensure the helper UI tells users they can **"Skip for now & email later"** to preserve momentum.
2. **Stripe Checkout Page (Step 5):** Reassure Irish homeowners by displaying Joe's **"100% Conflict-Free Guarantee"** and **"No Contractor Commission Kickbacks"** badges immediately adjacent to the payment redirect CTA.
3. **Bill / Carbon Tax Calculator (Step 2):** Test whether simplifying the bill input down to a quick dual-option toggle (e.g. "Low/Medium/High") increases completion speeds.

*This report is securely dispatched using modern edge-network integrations. If you need to tweak the reporting schema, check the administrative console.*
`;

    // 5. Convert Markdown to simple styled HTML for maximum email client compatibility
    const htmlBody = convertMarkdownToHtml(markdownBody, emailSubject);

    // 6. Send the Email via Resend (Primary) or SendGrid (Secondary)
    const recipient = process.env.JOE_EMAIL || 'joe@ecosmarthomes.ie';
    const sender = 'reports@ecosmarthomes.ie';

    if (resend) {
      console.log('✉️ Dispatched via Resend API...');
      await resend.emails.send({
        from: `EcoSmartHome Analytics <${sender}>`,
        to: recipient,
        subject: emailSubject,
        html: htmlBody,
        text: markdownBody,
      });
    } else if (process.env.SENDGRID_API_KEY) {
      console.log('✉️ Dispatched via SendGrid API...');
      await sgMail.send({
        to: recipient,
        from: `EcoSmartHome Analytics <${sender}>`,
        subject: emailSubject,
        html: htmlBody,
        text: markdownBody,
      });
    } else {
      console.log('⚠️ Email APIs not configured. Markdown payload preview:');
      console.log(markdownBody);
    }

    return new Response(JSON.stringify({ success: true, timestamp: new Date().toISOString() }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('❌ Failed to run weekly cron email:', error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }
}

// Helper: Maps step integer IDs to friendly marketing wizard names
function getStepFriendlyName(step) {
  switch (step) {
    case 1: return 'Property Profiler (Archetype & BER)';
    case 2: return 'Fuel & Carbon Tax Calculator (Slider)';
    case 3: return 'Gemini Vision Boiler Scanner (Uploader)';
    case 4: return 'SEAI Savings & Grant Estimator';
    case 5: return 'Actionable Roadmap Secure Checkout';
    default: return `Wizard Screen ${step}`;
  }
}

// Helper: Generates actionable advice based on Irish energy retrofitting metrics
function getActionRecommendation(step) {
  switch (step) {
    case 1: return 'Limit selection choices. Keep property archetype list to 4 options to avoid decision fatigue.';
    case 2: return 'Simplify slider mechanics. Pre-select Ireland’s median €3,100 kerosene annual bill value by default.';
    case 3: return 'Add a conspicuous bypass link ("Skip uploader, upload later") so on-the-go users don\'t drop out.';
    case 4: return 'Highlight the 16% property value appreciation value badge in bright emerald text to amplify financial excitement.';
    case 5: return 'Incorporate structural trust factors (Secure Stripe badge, Joes direct direct review, No installer kickbacks) above checkout.';
    default: return 'Review analytics session logs inside the administrator console to trace user flow behavior.';
  }
}

// Helper: Quick markdown-to-HTML conversion template to secure visual styling across Apple Mail, Outlook & Gmail
function convertMarkdownToHtml(md, title) {
  let html = md
    .replace(/^# (.*$)/gim, '<h1 style="color: #020617; font-family: sans-serif; font-size: 24px; font-weight: 800; margin-bottom: 8px; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px;">$1</h1>')
    .replace(/^## (.*$)/gim, '<h2 style="color: #0f172a; font-family: sans-serif; font-size: 18px; font-weight: 700; margin-top: 24px; margin-bottom: 12px; padding-bottom: 4px; border-bottom: 1px solid #f1f5f9;">$1</h2>')
    .replace(/^### (.*$)/gim, '<h3 style="color: #1e293b; font-family: sans-serif; font-size: 14px; font-weight: 700; margin-top: 18px; margin-bottom: 8px;">$1</h3>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>');

  const lines = html.split('\n');
  let insideTable = false;
  let tableRows = [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (line.startsWith('|')) {
      if (!insideTable) {
        insideTable = true;
        tableRows = [];
      }
      if (line.includes('---')) continue;
      
      const cells = line.split('|').filter(c => c.trim() !== '').map(c => c.trim());
      const isHeader = tableRows.length === 0;
      
      let rowHtml = '<tr style="' + (isHeader ? 'background-color: #f8fafc; border-bottom: 2px solid #cbd5e1;' : 'border-bottom: 1px solid #e2e8f0;') + '">';
      cells.forEach(cell => {
        rowHtml += isHeader 
          ? `<th style="padding: 10px 12px; text-align: left; font-family: sans-serif; font-size: 11px; font-weight: bold; color: #475569; text-transform: uppercase;">${cell}</th>`
          : `<td style="padding: 10px 12px; font-family: sans-serif; font-size: 12px; color: #334155;">${cell}</td>`;
      });
      rowHtml += '</tr>';
      tableRows.push(rowHtml);
    } else {
      if (insideTable) {
        insideTable = false;
        const tableHtml = `<table style="width: 100%; border-collapse: collapse; margin-top: 12px; margin-bottom: 24px; border: 1px solid #e2e8f0;">${tableRows.join('')}</table>`;
        lines[i - tableRows.length - 1] = tableHtml;
        for (let j = 1; j < tableRows.length + 1; j++) {
          const indexToRemove = i - j;
          if (lines[indexToRemove].trim().startsWith('|') || lines[indexToRemove].includes('</table>')) {
            lines[indexToRemove] = '';
          }
        }
      }
    }
  }

  html = lines.filter(l => l !== '').join('\n')
    .replace(/^\* (.*$)/gim, '<li style="margin-bottom: 6px; font-family: sans-serif; font-size: 13px; color: #334155;">$1</li>')
    .replace(/(<li.*<\/li>)/gms, '<ul style="padding-left: 20px; margin-bottom: 16px;">$1</ul>')
    .replace(/^(?!<h|<li|<ul|<table|<tr|<th|<td|<div)(.*$)/gim, '<p style="font-family: sans-serif; font-size: 13px; color: #334155; line-height: 1.6; margin-bottom: 14px;">$1</p>');

  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>${title}</title>
      </head>
      <body style="background-color: #f1f5f9; padding: 24px; margin: 0; -webkit-font-smoothing: antialiased;">
        <div style="max-width: 680px; margin: 0 auto; background-color: #ffffff; padding: 40px; border-radius: 16px; border: 1px solid #e2e8f0; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);">
          ${html}
        </div>
      </body>
    </html>
  `;
}
